name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Run Tests
      run: mvn -B clean test
      
    - name: Run PIT Mutation Tests
      run: mvn -B -pl gateway -am test-compile org.pitest:pitest-maven:1.15.0:mutationCoverage
